// 書籍ごとのテーマ（カードのポップ感のための色セット）。
// /books 一覧ページとトップページの教科書セクションで共有する。

export interface BookTheme {
  cardBg: string;
  iconBg: string;
  iconText: string;
  accent: string;
  accentHover: string;
  accentBg: string;
  badgeBg: string;
  badgeText: string;
  iconName: string;
}

export const DEFAULT_THEME: BookTheme = {
  cardBg: 'bg-amber-50',
  iconBg: 'bg-amber-100',
  iconText: 'text-amber-600',
  accent: 'text-amber-600',
  accentHover: 'group-hover:text-amber-700',
  accentBg: 'bg-amber-500',
  badgeBg: 'bg-amber-50',
  badgeText: 'text-amber-700',
  iconName: 'BookOpen',
};

const bookThemeMap: Record<string, BookTheme> = {
  zod: {
    cardBg: 'bg-sky-50',
    iconBg: 'bg-sky-100',
    iconText: 'text-sky-600',
    accent: 'text-sky-600',
    accentHover: 'group-hover:text-sky-700',
    accentBg: 'bg-sky-500',
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-700',
    iconName: 'Braces',
  },
  'system-design': {
    cardBg: 'bg-emerald-50',
    iconBg: 'bg-emerald-100',
    iconText: 'text-emerald-600',
    accent: 'text-emerald-600',
    accentHover: 'group-hover:text-emerald-700',
    accentBg: 'bg-emerald-500',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-700',
    iconName: 'Blocks',
  },
  javascript: {
    cardBg: 'bg-amber-50',
    iconBg: 'bg-amber-100',
    iconText: 'text-amber-600',
    accent: 'text-amber-600',
    accentHover: 'group-hover:text-amber-700',
    accentBg: 'bg-amber-400',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-700',
    iconName: 'Braces',
  },
  'html-basics': {
    cardBg: 'bg-red-50',
    iconBg: 'bg-red-100',
    iconText: 'text-red-600',
    accent: 'text-red-600',
    accentHover: 'group-hover:text-red-700',
    accentBg: 'bg-red-500',
    badgeBg: 'bg-red-50',
    badgeText: 'text-red-700',
    iconName: 'FileCode2',
  },
  'node-js': {
    cardBg: 'bg-sky-50',
    iconBg: 'bg-sky-100',
    iconText: 'text-sky-600',
    accent: 'text-sky-600',
    accentHover: 'group-hover:text-sky-700',
    accentBg: 'bg-sky-500',
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-700',
    iconName: 'Server',
  },
  fastify: {
    cardBg: 'bg-zinc-50',
    iconBg: 'bg-yellow-100',
    iconText: 'text-zinc-900',
    accent: 'text-yellow-700',
    accentHover: 'group-hover:text-yellow-800',
    accentBg: 'bg-yellow-500',
    badgeBg: 'bg-yellow-50',
    badgeText: 'text-yellow-800',
    iconName: 'Server',
  },
  docker: {
    cardBg: 'bg-sky-50',
    iconBg: 'bg-sky-100',
    iconText: 'text-sky-600',
    accent: 'text-sky-600',
    accentHover: 'group-hover:text-sky-700',
    accentBg: 'bg-sky-500',
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-700',
    iconName: 'Container',
  },
  typescript: {
    cardBg: 'bg-indigo-50',
    iconBg: 'bg-indigo-100',
    iconText: 'text-indigo-600',
    accent: 'text-indigo-600',
    accentHover: 'group-hover:text-indigo-700',
    accentBg: 'bg-indigo-500',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-700',
    iconName: 'FileCode2',
  },
  'react-learning': {
    cardBg: 'bg-cyan-50',
    iconBg: 'bg-cyan-100',
    iconText: 'text-cyan-600',
    accent: 'text-cyan-600',
    accentHover: 'group-hover:text-cyan-700',
    accentBg: 'bg-cyan-500',
    badgeBg: 'bg-cyan-50',
    badgeText: 'text-cyan-700',
    iconName: 'Atom',
  },
  'css-basics': {
    cardBg: 'bg-blue-50',
    iconBg: 'bg-blue-100',
    iconText: 'text-blue-600',
    accent: 'text-blue-600',
    accentHover: 'group-hover:text-blue-700',
    accentBg: 'bg-blue-500',
    badgeBg: 'bg-blue-50',
    badgeText: 'text-blue-700',
    iconName: 'Paintbrush',
  },
  'tailwind-css': {
    cardBg: 'bg-violet-50',
    iconBg: 'bg-violet-100',
    iconText: 'text-violet-600',
    accent: 'text-violet-600',
    accentHover: 'group-hover:text-violet-700',
    accentBg: 'bg-violet-500',
    badgeBg: 'bg-violet-50',
    badgeText: 'text-violet-700',
    iconName: 'Wind',
  },
  'cs-basics': {
    cardBg: 'bg-purple-50',
    iconBg: 'bg-purple-100',
    iconText: 'text-purple-600',
    accent: 'text-purple-600',
    accentHover: 'group-hover:text-purple-700',
    accentBg: 'bg-purple-500',
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-700',
    iconName: 'Cpu',
  },
  'next-js': {
    cardBg: 'bg-zinc-50',
    iconBg: 'bg-zinc-100',
    iconText: 'text-zinc-700',
    accent: 'text-zinc-700',
    accentHover: 'group-hover:text-zinc-900',
    accentBg: 'bg-zinc-800',
    badgeBg: 'bg-zinc-100',
    badgeText: 'text-zinc-700',
    iconName: 'Globe',
  },
  'git-basic': {
    cardBg: 'bg-rose-50',
    iconBg: 'bg-rose-100',
    iconText: 'text-rose-600',
    accent: 'text-rose-600',
    accentHover: 'group-hover:text-rose-700',
    accentBg: 'bg-rose-500',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-700',
    iconName: 'GitBranch',
  },
  'unit-testing': {
    cardBg: 'bg-slate-50',
    iconBg: 'bg-slate-100',
    iconText: 'text-slate-600',
    accent: 'text-slate-600',
    accentHover: 'group-hover:text-slate-700',
    accentBg: 'bg-slate-500',
    badgeBg: 'bg-slate-100',
    badgeText: 'text-slate-700',
    iconName: 'FlaskConical',
  },
  'http-and-web-api': {
    cardBg: 'bg-orange-50',
    iconBg: 'bg-orange-100',
    iconText: 'text-orange-600',
    accent: 'text-orange-600',
    accentHover: 'group-hover:text-orange-700',
    accentBg: 'bg-orange-500',
    badgeBg: 'bg-orange-50',
    badgeText: 'text-orange-700',
    iconName: 'Globe2',
  },
  'sql-basics': {
    cardBg: 'bg-fuchsia-50',
    iconBg: 'bg-fuchsia-100',
    iconText: 'text-fuchsia-600',
    accent: 'text-fuchsia-600',
    accentHover: 'group-hover:text-fuchsia-700',
    accentBg: 'bg-fuchsia-500',
    badgeBg: 'bg-fuchsia-50',
    badgeText: 'text-fuchsia-700',
    iconName: 'Database',
  },
  mysql: {
    cardBg: 'bg-yellow-50',
    iconBg: 'bg-yellow-100',
    iconText: 'text-yellow-700',
    accent: 'text-yellow-700',
    accentHover: 'group-hover:text-yellow-800',
    accentBg: 'bg-yellow-500',
    badgeBg: 'bg-yellow-50',
    badgeText: 'text-yellow-800',
    iconName: 'Database',
  },
  sqlite: {
    cardBg: 'bg-pink-50',
    iconBg: 'bg-pink-100',
    iconText: 'text-pink-600',
    accent: 'text-pink-600',
    accentHover: 'group-hover:text-pink-700',
    accentBg: 'bg-pink-500',
    badgeBg: 'bg-pink-50',
    badgeText: 'text-pink-700',
    iconName: 'Database',
  },
  'integration-and-e2e-testing': {
    cardBg: 'bg-teal-50',
    iconBg: 'bg-teal-100',
    iconText: 'text-teal-600',
    accent: 'text-teal-600',
    accentHover: 'group-hover:text-teal-700',
    accentBg: 'bg-teal-500',
    badgeBg: 'bg-teal-50',
    badgeText: 'text-teal-700',
    iconName: 'TestTube2',
  },
  'aws-saa-c03': {
    cardBg: 'bg-orange-50',
    iconBg: 'bg-orange-100',
    iconText: 'text-orange-600',
    accent: 'text-orange-600',
    accentHover: 'group-hover:text-orange-700',
    accentBg: 'bg-orange-500',
    badgeBg: 'bg-orange-50',
    badgeText: 'text-orange-700',
    iconName: 'Cloud',
  },
  'azure-az-900': {
    cardBg: 'bg-blue-50',
    iconBg: 'bg-blue-100',
    iconText: 'text-blue-600',
    accent: 'text-blue-600',
    accentHover: 'group-hover:text-blue-700',
    accentBg: 'bg-blue-500',
    badgeBg: 'bg-blue-50',
    badgeText: 'text-blue-700',
    iconName: 'Cloud',
  },
  'github-actions': {
    cardBg: 'bg-indigo-50',
    iconBg: 'bg-indigo-100',
    iconText: 'text-indigo-600',
    accent: 'text-indigo-600',
    accentHover: 'group-hover:text-indigo-700',
    accentBg: 'bg-indigo-500',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-700',
    iconName: 'GitBranch',
  },
  'coding-test': {
    cardBg: 'bg-lime-50',
    iconBg: 'bg-lime-100',
    iconText: 'text-lime-700',
    accent: 'text-lime-700',
    accentHover: 'group-hover:text-lime-800',
    accentBg: 'bg-lime-500',
    badgeBg: 'bg-lime-50',
    badgeText: 'text-lime-700',
    iconName: 'Braces',
  },
  csharp: {
    cardBg: 'bg-green-50',
    iconBg: 'bg-green-100',
    iconText: 'text-green-700',
    accent: 'text-green-700',
    accentHover: 'group-hover:text-green-800',
    accentBg: 'bg-green-600',
    badgeBg: 'bg-green-50',
    badgeText: 'text-green-700',
    iconName: 'Hash',
  },
  'ai-agent-development': {
    cardBg: 'bg-stone-50',
    iconBg: 'bg-stone-100',
    iconText: 'text-stone-700',
    accent: 'text-stone-700',
    accentHover: 'group-hover:text-stone-800',
    accentBg: 'bg-stone-600',
    badgeBg: 'bg-stone-50',
    badgeText: 'text-stone-700',
    iconName: 'Bot',
  },
};

/** bookSlug に対応するテーマを返す。未登録の本は DEFAULT_THEME（amber）。 */
export function getBookTheme(bookSlug: string): BookTheme {
  return bookThemeMap[bookSlug] ?? DEFAULT_THEME;
}
