export const BOOK_SEARCH_SUGGESTIONS: Record<string, readonly string[]> = {
  'aws-saa-c03': [
    'IAM',
    'VPC',
    'S3',
    'EC2',
    'Lambda',
    'RDS',
    'Aurora',
    'DynamoDB',
    'CloudFront',
    'Route 53',
    'SQS',
    'SNS',
    'EventBridge',
    'KMS',
    'WAF',
    'Secrets Manager',
    'Auto Scaling',
    'NAT Gateway',
    'VPC Endpoint',
    'OpenSearch',
    'Kinesis',
    'Firehose',
    'Glue',
    'Athena',
    'ECS',
    'CloudWatch',
    'CloudFormation',
    'CDK',
    'バケットポリシー',
  ],

  'azure-az-900': [
    'Entra ID',
    'RBAC',
    'VNet',
    '仮想マシン',
    'App Service',
    'Azure Functions',
    'AKS',
    'ExpressRoute',
    'VPN Gateway',
    '可用性ゾーン',
    'リージョン',
    'サブスクリプション',
    'リソースグループ',
    'IaaS',
    'PaaS',
    'SaaS',
    'SLA',
    'MFA',
    '条件付きアクセス',
    'ゼロトラスト',
  ],

  'http-and-web-api': ['CORS', 'SSH'],

  'sql-basics': [
    'SELECT',
    'WHERE',
    'JOIN',
    'GROUP BY',
    'HAVING',
    'NULL',
    'COALESCE',
    'EXISTS',
    '正規化',
    '制約',
    'インデックス',
    'トランザクション',
    'SQLインジェクション',
  ],

  'integration-and-e2e-testing': ['E2E', '統合テスト', 'モック', 'CI'],

  'system-design': ['要件定義', 'DB設計', 'API設計', '認証', 'エラー設計'],

  javascript: [
    'Promise',
    'async',
    'fetch',
    'JSON',
    'Date',
    'Map',
    '配列',
    '文字列',
    '分割代入',
    'class',
    'this',
    'map',
    'filter',
    'reduce',
    'find',
    'findIndex',
    'some',
    'every',
    'includes',
    'slice',
    'concat',
    'sort',
    'splice',
    'flatMap',
  ],

  'node-js': [
    'npm',
    'package.json',
    'CommonJS',
    'ES Modules',
    'EventEmitter',
    'イベントループ',
    'Buffer',
    'Stream',
    'fs',
    'process',
    'Express',
    '環境変数',
    'CORS',
    'node:test',
    'Docker',
  ],

  typescript: ['ユニオン型', 'ジェネリクス', '型ガード', 'Utility Types', 'tsconfig'],

  'react-learning': ['useState', 'useEffect', 'useMemo', 'useCallback', '依存配列'],

  'css-basics': ['Flexbox', 'Grid', 'レスポンシブ', '詳細度', 'CSS変数'],

  'tailwind-css': ['flex', 'grid', 'レスポンシブ', 'dark', 'theme'],

  'unit-testing': ['単体テスト', 'モック', 'リファクタリング', 'テスト構造', 'メソッド'],

  'coding-test': [
    '計算量',
    'Big-O',
    '二分探索',
    '尺取り法',
    '累積和',
    'DFS',
    'BFS',
    '貪欲法',
    'DP',
    'ナップサック',
    'Union-Find',
    'ダイクストラ',
  ],

  'github-actions': [
    'workflow',
    'CI/CD',
    'on push',
    'jobs',
    'steps',
    'actions/checkout',
    'secrets',
    'matrix',
    'cache',
    'artifact',
    'OIDC',
    'deploy',
  ],

  'git-basic': [
    'commit',
    'branch',
    'merge',
    'rebase',
    'stash',
    'reset',
    'revert',
    'restore',
    'fetch',
    'pull',
    'push',
    'conflict',
  ],

  'cs-basics': ['CPU', 'メモリ', 'データ構造', 'ネットワーク', 'SSH', 'デバッグ'],

  'next-js': [
    'use client',
    'use server',
    'Server Components',
    'Client Components',
    'Route Handler',
    'Server Actions',
    'metadata',
    'middleware',
    'layout',
    'loading',
    'error',
    'fetch',
    'cache',
    'revalidate',
    'dynamic routes',
  ],
};
